services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\RadiusVlanBundle\:
        resource: '../../'
        exclude: '../../{Entity,Resources,Tests}'
